import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/layouts/Navbar";
import Footer from "@/layouts/Footer";
import { QueryClient } from "@tanstack/react-query";
import ClientWrapper from "./ClientWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient =new QueryClient()

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="py-1 px-5">
          <Navbar></Navbar>
        </header>
        <main className="min-h-[calc(100vh-302px)]">
          <ClientWrapper>

          {children}
          </ClientWrapper>
        </main>
        <footer>
          <Footer></Footer>
        </footer>
        </body>
    </html>
  );
}
